### PR TITLE
Feature: Common base class for windows Hello and DPAPI keychains

### PR DESCRIPTION
**Pull request by infeo**
This PR changes the architecture of the windows keychain access service providers.

A base class `WindowsKeychainAccessBase` serves as the foundation for the service providers. It splits the keychain functionality into two parts:
1. storage - given by the `Keychain` interface and it current only impl `FileKeychain`
2. encryption - given by the `PassphraseCryptor` interface and its DPAPI and WindowsHello impls.

Additionally, more unit tests were added to test the single components.

### CODE REVIEW

**Comment by purejava** [comment]
Hi @infeo, I run your changes, but none of the `KeychainAccessProvider`s is loaded on startup.
My first guess was, that `WindowsKeychainAccessBase` is missing in `module-info.java`, but that's not possible for an abstract class.

Any idea?

**Comment by infeo** [comment]
To quote infamous words:
> works on my machine ¯\_(ツ)_/¯

I assume you tried an end-to-end test. Did you checked out the correct branch, then did a `mvn clean install` and then changed integrations-win version to  `1.4.0-SNAPSHOT` in the Cryptomator pom? (note that you might have to reload the project in the IDE).

**Comment by purejava** [comment]
Yes, I am aware, that IntelliJ has some caching and deleted the ~/.m2/repository directory yesterday. before I started the test and lauched the IDE afterwards.

I am using your changed together with https://github.com/purejava/cryptomator/tree/2ndfactor.

I re-tested this morning. Again, no luck:
```java
06:32:51.378 [JavaFX Application Thread] DEBUG o.c.ui.fxapp.FxApplicationTerminator - Enabling sudden termination
06:32:51.394 [JavaFX Application Thread] DEBUG o.c.i.common.ClassLoaderFactory - Found jars in cryptomator.pluginDir: 
06:32:51.407 [JavaFX Application Thread] DEBUG o.c.i.common.IntegrationsLoader - TrayMenuController: Found implementation: org.cryptomator.ui.traymenu.AwtTrayMenuController in jar /C:/Users/Ralph%20Plawetzki/IdeaProjects/cryptomator/target/classes/
06:32:51.435 [JavaFX Application Thread] DEBUG o.c.i.common.IntegrationsLoader - TrayMenuController: Implementation is available: org.cryptomator.ui.traymenu.AwtTrayMenuController
06:32:51.917 [JavaFX Application Thread] DEBUG o.c.u.traymenu.AwtTrayMenuController - initialized tray icon
06:32:51.973 [JavaFX Application Thread] DEBUG o.cryptomator.common.CommonsModule - Starting App Background Thread 001
06:32:53.805 [JavaFX Application Thread] DEBUG o.c.i.common.ClassLoaderFactory - Found jars in cryptomator.pluginDir: 
06:32:54.011 [JavaFX Application Thread] DEBUG o.cryptomator.ui.common.FontLoader - Loaded family: Font Awesome 5 Free Solid
06:32:54.188 [JavaFX Application Thread] DEBUG o.c.i.common.ClassLoaderFactory - Found jars in cryptomator.pluginDir: 
06:32:54.271 [JavaFX Application Thread] TRACE o.c.u.m.MainWindowController - init MainWindowController
06:32:55.210 [JavaFX Application Thread] DEBUG o.cryptomator.ui.fxapp.FxApplication - Main window initialized after 7747ms
06:32:58.626 [JavaFX Application Thread] DEBUG o.cryptomator.common.CommonsModule - Starting App Background Thread 002
06:32:58.626 [JavaFX Application Thread] DEBUG o.cryptomator.ui.fxapp.UpdateChecker - Checking for updates...
06:32:59.412 [JavaFX Application Thread] INFO  o.cryptomator.ui.fxapp.UpdateChecker - Current version: SNAPSHOT, latest version: 1.14.2
06:32:59.673 [JavaFX Application Thread] DEBUG o.c.i.common.ClassLoaderFactory - Found jars in cryptomator.pluginDir: 
06:32:59.676 [JavaFX Application Thread] DEBUG o.c.i.common.IntegrationsLoader - AutoStartProvider: Found implementation: org.cryptomator.windows.autostart.WindowsAutoStart in jar /C:/Users/Ralph%20Plawetzki/.m2/repository/org/cryptomator/integrations-win/1.4.0-SNAPSHOT/integrations-win-1.4.0-SNAPSHOT.jar
06:32:59.716 [JavaFX Application Thread] DEBUG o.c.i.common.IntegrationsLoader - AutoStartProvider: Implementation is available: org.cryptomator.windows.autostart.WindowsAutoStart
06:32:59.721 [JavaFX Application Thread] DEBUG o.c.i.common.ClassLoaderFactory - Found jars in cryptomator.pluginDir: 
06:32:59.723 [JavaFX Application Thread] DEBUG o.c.i.common.IntegrationsLoader - QuickAccessService: Found implementation: org.cryptomator.windows.quickaccess.ExplorerQuickAccessService in jar /C:/Users/Ralph%20Plawetzki/.m2/repository/org/cryptomator/integrations-win/1.4.0-SNAPSHOT/integrations-win-1.4.0-SNAPSHOT.jar
06:32:59.725 [JavaFX Application Thread] DEBUG o.c.i.common.IntegrationsLoader - QuickAccessService: Implementation is available: org.cryptomator.windows.quickaccess.ExplorerQuickAccessService
06:33:00.758 [App Scheduled Executor 02] DEBUG o.c.common.settings.SettingsProvider - Attempting to save settings to C:\Users\Ralph Plawetzki\AppData\Roaming\Cryptomator\settings.json
06:33:01.240 [App Scheduled Executor 02] INFO  o.c.common.settings.SettingsProvider - Settings saved to C:\Users\Ralph Plawetzki\AppData\Roaming\Cryptomator\settings.json
```

**Comment by infeo** [comment]
The project itself contains an integration test for loading the DPAPI keychain: `WindowsProtectedKeychainAccessIntegrationTest`.

It is also executed on `mvn clean install` or explicitly with `mvn clean test`. If it does not fail, loading the services with Java SPI works (Cryptomator isn't doing anything else). You actually can also just use the plain cryptomator/develop, since we didn't change the API.

**Comment by purejava** [comment]
I could not reliably reproduce the issue with no KeychainAccessProvider loaded. It happens sometimes on compiling, sometimes not. So I'm merging this now.

**Pull request merged**
